Create Event Templates to be used in the Pilot
world-federation-of-advertisers/us-pilot-event-templates pull request #2
Opened 2022-08-09 18:10 UTC by uakyol

2022-08-09 19:24 UTC, uakyol commented
com_google_protobuf can be depended through common_jvm, I depended on it for the sake of saving time. This also provides _java_proto.

2022-08-09 21:50 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons, @SanjayVas, and @uakyol)

___
*[`build/repositories.bzl` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N93_NEQCIUsvc6meXkH:-N93_NEQCIUsvc6meXkI:b-t7siiv) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/0ff22b84457aac8c7908cd71cc8102c9955b50ad/build/repositories.bzl#L25)):*
> ```Starlark
> 
>     wfa_repo_archive(
>         name = "wfa_common_jvm",
> ```

do we want to have this repo depend on wfa_common_jvm?

We don't necessarily need to expose java_proto_library here, just proto_library. Additionally, if we're going to expose java_proto_library, maybe we should expose kt_jvm_proto_library. However, imo, we should not include comon_jvm and not expose language specific libraries.



_Code quote:_
```Starlark
wfa_common_jvm
```


<!-- Sent from Reviewable.io -->

2022-08-09 22:04 UTC, SanjayVas reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`build/repositories.bzl` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N93_NEQCIUsvc6meXkH:-N93cs0UCfh10JAv8qme:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/0ff22b84457aac8c7908cd71cc8102c9955b50ad/build/repositories.bzl#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we want to have this repo depend on wfa_common_jvm?

We don't necessarily need to expose java_proto_library here, just proto_library. Additionally, if we're going to expose java_proto_library, maybe we should expose kt_jvm_proto_library. However, imo, we should not include comon_jvm and not expose language specific libraries.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-08-10 16:27 UTC, uakyol commented
*[`build/repositories.bzl` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N93_NEQCIUsvc6meXkH:-N97ZDsg1RnAhq821u4T:bqnvro9) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/0ff22b84457aac8c7908cd71cc8102c9955b50ad/build/repositories.bzl#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Sorry, I tried to address this in a comment on the PR but I probably should have written that in Reviewable. -> 

"com_google_protobuf can be depended through common_jvm, I depended on it for the sake of saving time. This also provides _java_proto."


So, cross-media-measurement gets the proto_library dependency  through common_jvm. I see 2 options :

1) Extract the proto_library dependency from common_jvm and use it here.
2) Leave this PR as is, get the other dependencies for free. In fact why not even add the kt_jvm_proto_library.

I am voting for 2) since this is just a temporary implementation for the pilot and I see no downside of having this dependency, it also gives the edps  kt_jvm_proto_library for free.

What do you think?


<!-- Sent from Reviewable.io -->

2022-08-10 17:38 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons, @SanjayVas, and @uakyol)

___
*[`build/repositories.bzl` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N93_NEQCIUsvc6meXkH:-N97pZU45LZG561VtTqq:b-2jjh9s) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/0ff22b84457aac8c7908cd71cc8102c9955b50ad/build/repositories.bzl#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Sorry, I tried to address this in a comment on the PR but I probably should have written that in Reviewable. -> 

"com_google_protobuf can be depended through common_jvm, I depended on it for the sake of saving time. This also provides _java_proto."


So, cross-media-measurement gets the proto_library dependency  through common_jvm. I see 2 options :

1) Extract the proto_library dependency from common_jvm and use it here.
2) Leave this PR as is, get the other dependencies for free. In fact why not even add the kt_jvm_proto_library.

I am voting for 2) since this is just a temporary implementation for the pilot and I see no downside of having this dependency, it also gives the edps  kt_jvm_proto_library for free.

What do you think?

</blockquote></details>

You should do it similar to how cross-media-measurement-api does it
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1a89d37d6551d3ee477f1c74969104ecb00c9c43/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel#L1


<!-- Sent from Reviewable.io -->

2022-08-10 18:09 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`build/repositories.bzl` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N93_NEQCIUsvc6meXkH:-N97wbCwDMLPUeruMM1M:b-munwrr) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/0ff22b84457aac8c7908cd71cc8102c9955b50ad/build/repositories.bzl#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

You should do it similar to how cross-media-measurement-api does it
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/1a89d37d6551d3ee477f1c74969104ecb00c9c43/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel#L1
</blockquote></details>

Thanks, updated


<!-- Sent from Reviewable.io -->

2022-08-10 21:26 UTC, SanjayVas approved these changes
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons, @stevenwarejones, and @uakyol)

___
*[`src/main/proto/event_templates/BUILD.bazel` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N98dPCjEWFtHrkWjhQy:-N98dPCkDfJhwNtalAyj:b-r26ndl) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/6b3dee6a8c62264110e7de7e4306d319db2731ed/src/main/proto/event_templates/BUILD.bazel#L4)):*
> ```Starlark
> 
> package(
>     default_testonly = True,
> ```

I don't think this is true, as it'll be used in non-test code. It'll still be proof-of-concept code and therefore not likely survive very long, but it's still not test code.



_Code quote:_
```Starlark
default_testonly = True,
```


<!-- Sent from Reviewable.io -->

2022-08-11 14:23 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/event_templates/BUILD.bazel` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2#-N98dPCjEWFtHrkWjhQy:-N9CHVJwCl9JPy1m3JnG:bw8en0s) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/6b3dee6a8c62264110e7de7e4306d319db2731ed/src/main/proto/event_templates/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is true, as it'll be used in non-test code. It'll still be proof-of-concept code and therefore not likely survive very long, but it's still not test code.
</blockquote></details>

ah thank you!


<!-- Sent from Reviewable.io -->

2022-08-11 15:26 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-08-11 18:02 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)



<!-- Sent from Reviewable.io -->

2022-08-11 20:36 UTC, merged